name: "Feature Request"
description: "Suggest a new feature or improvement."
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request"

  - type: textarea
    id: solution
    attributes:
      label: "Describe the feature you'd like"
      description: "A clear and concise description of the feature you want to add."
      placeholder: "Describe the desired feature here."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "List alternative solutions here."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Provide additional context here."

  - type: textarea
    id: implementation-details
    attributes:
      label: "Implementation Details (Optional)"
      description: "If you have an idea of how this could be implemented, please share some details here."
      placeholder: "Provide implementation details here."
