worlds:
  preset-example:
    void: true
    folder: Tier 1
    name: Tier 1
    icon: GRASS_BLOCK
    description:
    - Small island
  random-world:
    void: false
    folder: Tier 2
    name: Random World
    icon: GRASS_BLOCK
    description:
    - Randomly generated world


