name: PlayerHousing
author: wildmaster84
api-version: 1.13
description: "This sucked to make :("
main: net.myteria.PlayerHousing
version: "3.0.0"
depend: []
folia-supported: true
commands:
  visit:
    description: visit command
    usage: /visit <player>
  housing:
    description: housing command
    usage: /housing